import { MigrationInterface, QueryRunner } from 'typeorm';

export class CountriesMigration1627173561496 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    queryRunner.query(`INSERT INTO public.country ("name", "iso") VALUES ('Afghanistan', 'AF');
        INSERT INTO public.country ("name", "iso") VALUES ('Albania', 'AL');
        INSERT INTO public.country ("name", "iso") VALUES ('Algeria', 'DZ');
        INSERT INTO public.country ("name", "iso") VALUES ('American Samoa', 'AS');
        INSERT INTO public.country ("name", "iso") VALUES ('Andorra', 'AD');
        INSERT INTO public.country ("name", "iso") VALUES ('Angola', 'AO');
        INSERT INTO public.country ("name", "iso") VALUES ('Anguilla', 'AI');
        INSERT INTO public.country ("name", "iso") VALUES ('Antarctica', 'AQ');
        INSERT INTO public.country ("name", "iso") VALUES ('Antigua and Barbuda', 'AG');
        INSERT INTO public.country ("name", "iso") VALUES ('Argentina', 'AR');
        INSERT INTO public.country ("name", "iso") VALUES ('Armenia', 'AM');
        INSERT INTO public.country ("name", "iso") VALUES ('Aruba', 'AW');
        INSERT INTO public.country ("name", "iso") VALUES ('Australia', 'AU');
        INSERT INTO public.country ("name", "iso") VALUES ('Austria', 'AT');
        INSERT INTO public.country ("name", "iso") VALUES ('Azerbaijan', 'AZ');
        INSERT INTO public.country ("name", "iso") VALUES ('Bahamas', 'BS');
        INSERT INTO public.country ("name", "iso") VALUES ('Bahrain', 'BH');
        INSERT INTO public.country ("name", "iso") VALUES ('Bangladesh', 'BD');
        INSERT INTO public.country ("name", "iso") VALUES ('Barbados', 'BB');
        INSERT INTO public.country ("name", "iso") VALUES ('Belarus', 'BY');
        INSERT INTO public.country ("name", "iso") VALUES ('Belgium', 'BE');
        INSERT INTO public.country ("name", "iso") VALUES ('Belize', 'BZ');
        INSERT INTO public.country ("name", "iso") VALUES ('Benin', 'BJ');
        INSERT INTO public.country ("name", "iso") VALUES ('Bermuda', 'BM');
        INSERT INTO public.country ("name", "iso") VALUES ('Bhutan', 'BT');
        INSERT INTO public.country ("name", "iso") VALUES ('Bosnia and Herzegovina', 'BA');
        INSERT INTO public.country ("name", "iso") VALUES ('Botswana', 'BW');
        INSERT INTO public.country ("name", "iso") VALUES ('Bouvet Island', 'BV');
        INSERT INTO public.country ("name", "iso") VALUES ('Brazil', 'BR');
        INSERT INTO public.country ("name", "iso") VALUES ('British Indian Ocean Territory', 'IO');
        INSERT INTO public.country ("name", "iso") VALUES ('Brunei Darussalam', 'BN');
        INSERT INTO public.country ("name", "iso") VALUES ('Bulgaria', 'BG');
        INSERT INTO public.country ("name", "iso") VALUES ('Burkina Faso', 'BF');
        INSERT INTO public.country ("name", "iso") VALUES ('Burundi', 'BI');
        INSERT INTO public.country ("name", "iso") VALUES ('Cambodia', 'KH');
        INSERT INTO public.country ("name", "iso") VALUES ('Cameroon', 'CM');
        INSERT INTO public.country ("name", "iso") VALUES ('Canada', 'CA');
        INSERT INTO public.country ("name", "iso") VALUES ('Cape Verde', 'CV');
        INSERT INTO public.country ("name", "iso") VALUES ('Cayman Islands', 'KY');
        INSERT INTO public.country ("name", "iso") VALUES ('Central African Republic', 'CF');
        INSERT INTO public.country ("name", "iso") VALUES ('Chad', 'TD');
        INSERT INTO public.country ("name", "iso") VALUES ('Chile', 'CL');
        INSERT INTO public.country ("name", "iso") VALUES ('China', 'CN');
        INSERT INTO public.country ("name", "iso") VALUES ('Christmas Island', 'CX');
        INSERT INTO public.country ("name", "iso") VALUES ('Cocos (Keeling) Islands', 'CC');
        INSERT INTO public.country ("name", "iso") VALUES ('Colombia', 'CO');
        INSERT INTO public.country ("name", "iso") VALUES ('Comoros', 'KM');
        INSERT INTO public.country ("name", "iso") VALUES ('Congo', 'CG');
        INSERT INTO public.country ("name", "iso") VALUES ('Cook Islands', 'CK');
        INSERT INTO public.country ("name", "iso") VALUES ('Costa Rica', 'CR');
        INSERT INTO public.country ("name", "iso") VALUES ('Croatia', 'HR');
        INSERT INTO public.country ("name", "iso") VALUES ('Cuba', 'CU');
        INSERT INTO public.country ("name", "iso") VALUES ('Cyprus', 'CY');
        INSERT INTO public.country ("name", "iso") VALUES ('Czech Republic', 'CZ');
        INSERT INTO public.country ("name", "iso") VALUES ('Denmark', 'DK');
        INSERT INTO public.country ("name", "iso") VALUES ('Djibouti', 'DJ');
        INSERT INTO public.country ("name", "iso") VALUES ('Dominica', 'DM');
        INSERT INTO public.country ("name", "iso") VALUES ('Dominican Republic', 'DO');
        INSERT INTO public.country ("name", "iso") VALUES ('Ecuador', 'EC');
        INSERT INTO public.country ("name", "iso") VALUES ('Egypt', 'EG');
        INSERT INTO public.country ("name", "iso") VALUES ('El Salvador', 'SV');
        INSERT INTO public.country ("name", "iso") VALUES ('Equatorial Guinea', 'GQ');
        INSERT INTO public.country ("name", "iso") VALUES ('Eritrea', 'ER');
        INSERT INTO public.country ("name", "iso") VALUES ('Estonia', 'EE');
        INSERT INTO public.country ("name", "iso") VALUES ('Ethiopia', 'ET');
        INSERT INTO public.country ("name", "iso") VALUES ('Falkland Islands (Malvinas)' ,'FK');
        INSERT INTO public.country ("name", "iso") VALUES ('Faroe Islands', 'FO');
        INSERT INTO public.country ("name", "iso") VALUES ('Fiji', 'FJ');
        INSERT INTO public.country ("name", "iso") VALUES ('Finland', 'FI');
        INSERT INTO public.country ("name", "iso") VALUES ('France', 'FR');
        INSERT INTO public.country ("name", "iso") VALUES ('French Guiana', 'GF');
        INSERT INTO public.country ("name", "iso") VALUES ('French Polynesia', 'PF');
        INSERT INTO public.country ("name", "iso") VALUES ('French Southern Territories', 'TF');
        INSERT INTO public.country ("name", "iso") VALUES ('Gabon', 'GA');
        INSERT INTO public.country ("name", "iso") VALUES ('Gambia', 'GM');
        INSERT INTO public.country ("name", "iso") VALUES ('Georgia', 'GE');
        INSERT INTO public.country ("name", "iso") VALUES ('Germany', 'DE');
        INSERT INTO public.country ("name", "iso") VALUES ('Ghana', 'GH');
        INSERT INTO public.country ("name", "iso") VALUES ('Gibraltar', 'GI');
        INSERT INTO public.country ("name", "iso") VALUES ('Greece', 'GR');
        INSERT INTO public.country ("name", "iso") VALUES ('Greenland', 'GL');
        INSERT INTO public.country ("name", "iso") VALUES ('Grenada', 'GD');
        INSERT INTO public.country ("name", "iso") VALUES ('Guadeloupe', 'GP');
        INSERT INTO public.country ("name", "iso") VALUES ('Guam', 'GU');
        INSERT INTO public.country ("name", "iso") VALUES ('Guatemala', 'GT');
        INSERT INTO public.country ("name", "iso") VALUES ('Guernsey', 'GG');
        INSERT INTO public.country ("name", "iso") VALUES ('Guinea', 'GN');
        INSERT INTO public.country ("name", "iso") VALUES ('Guinea-Bissau', 'GW');
        INSERT INTO public.country ("name", "iso") VALUES ('Guyana', 'GY');
        INSERT INTO public.country ("name", "iso") VALUES ('Haiti', 'HT');
        INSERT INTO public.country ("name", "iso") VALUES ('Heard Island and McDonald Islands', 'HM');
        INSERT INTO public.country ("name", "iso") VALUES ('Holy See (Vatican City State)' ,'VA');
        INSERT INTO public.country ("name", "iso") VALUES ('Honduras', 'HN');
        INSERT INTO public.country ("name", "iso") VALUES ('Hong Kong', 'HK');
        INSERT INTO public.country ("name", "iso") VALUES ('Hungary', 'HU');
        INSERT INTO public.country ("name", "iso") VALUES ('Iceland', 'IS');
        INSERT INTO public.country ("name", "iso") VALUES ('India', 'IN');
        INSERT INTO public.country ("name", "iso") VALUES ('Indonesia', 'ID');
        INSERT INTO public.country ("name", "iso") VALUES ('Iraq', 'IQ');
        INSERT INTO public.country ("name", "iso") VALUES ('Ireland', 'IE');
        INSERT INTO public.country ("name", "iso") VALUES ('Isle of Man', 'IM');
        INSERT INTO public.country ("name", "iso") VALUES ('Israel', 'IL');
        INSERT INTO public.country ("name", "iso") VALUES ('Italy', 'IT');
        INSERT INTO public.country ("name", "iso") VALUES ('Jamaica', 'JM');
        INSERT INTO public.country ("name", "iso") VALUES ('Japan', 'JP');
        INSERT INTO public.country ("name", "iso") VALUES ('Jersey', 'JE');
        INSERT INTO public.country ("name", "iso") VALUES ('Jordan', 'JO');
        INSERT INTO public.country ("name", "iso") VALUES ('Kazakhstan', 'KZ');
        INSERT INTO public.country ("name", "iso") VALUES ('Kenya', 'KE');
        INSERT INTO public.country ("name", "iso") VALUES ('Kiribati', 'KI');
        INSERT INTO public.country ("name", "iso") VALUES ('Kuwait', 'KW');
        INSERT INTO public.country ("name", "iso") VALUES ('Kyrgyzstan', 'KG');
        INSERT INTO public.country ("name", "iso") VALUES ('Lao Peoples Democratic Republic', 'LA');
        INSERT INTO public.country ("name", "iso") VALUES ('Latvia', 'LV');
        INSERT INTO public.country ("name", "iso") VALUES ('Lebanon', 'LB');
        INSERT INTO public.country ("name", "iso") VALUES ('Lesotho', 'LS');
        INSERT INTO public.country ("name", "iso") VALUES ('Liberia', 'LR');
        INSERT INTO public.country ("name", "iso") VALUES ('Libya', 'LY');
        INSERT INTO public.country ("name", "iso") VALUES ('Liechtenstein', 'LI');
        INSERT INTO public.country ("name", "iso") VALUES ('Lithuania', 'LT');
        INSERT INTO public.country ("name", "iso") VALUES ('Luxembourg', 'LU');
        INSERT INTO public.country ("name", "iso") VALUES ('Macao', 'MO');
        INSERT INTO public.country ("name", "iso") VALUES ('Madagascar', 'MG');
        INSERT INTO public.country ("name", "iso") VALUES ('Malawi', 'MW');
        INSERT INTO public.country ("name", "iso") VALUES ('Malaysia', 'MY');
        INSERT INTO public.country ("name", "iso") VALUES ('Maldives', 'MV');
        INSERT INTO public.country ("name", "iso") VALUES ('Mali', 'ML');
        INSERT INTO public.country ("name", "iso") VALUES ('Malta', 'MT');
        INSERT INTO public.country ("name", "iso") VALUES ('Marshall Islands', 'MH');
        INSERT INTO public.country ("name", "iso") VALUES ('Martinique', 'MQ');
        INSERT INTO public.country ("name", "iso") VALUES ('Mauritania', 'MR');
        INSERT INTO public.country ("name", "iso") VALUES ('Mauritius', 'MU');
        INSERT INTO public.country ("name", "iso") VALUES ('Mayotte', 'YT');
        INSERT INTO public.country ("name", "iso") VALUES ('Mexico', 'MX');
        INSERT INTO public.country ("name", "iso") VALUES ('Monaco', 'MC');
        INSERT INTO public.country ("name", "iso") VALUES ('Mongolia', 'MN');
        INSERT INTO public.country ("name", "iso") VALUES ('Montenegro', 'ME');
        INSERT INTO public.country ("name", "iso") VALUES ('Montserrat', 'MS');
        INSERT INTO public.country ("name", "iso") VALUES ('Morocco', 'MA');
        INSERT INTO public.country ("name", "iso") VALUES ('Mozambique', 'MZ');
        INSERT INTO public.country ("name", "iso") VALUES ('Myanmar', 'MM');
        INSERT INTO public.country ("name", "iso") VALUES ('Namibia', 'NA');
        INSERT INTO public.country ("name", "iso") VALUES ('Nauru', 'NR');
        INSERT INTO public.country ("name", "iso") VALUES ('Nepal', 'NP');
        INSERT INTO public.country ("name", "iso") VALUES ('Netherlands', 'NL');
        INSERT INTO public.country ("name", "iso") VALUES ('New Caledonia', 'NC');
        INSERT INTO public.country ("name", "iso") VALUES ('New Zealand', 'NZ');
        INSERT INTO public.country ("name", "iso") VALUES ('Nicaragua', 'NI');
        INSERT INTO public.country ("name", "iso") VALUES ('Niger', 'NE');
        INSERT INTO public.country ("name", "iso") VALUES ('Nigeria', 'NG');
        INSERT INTO public.country ("name", "iso") VALUES ('Niue', 'NU');
        INSERT INTO public.country ("name", "iso") VALUES ('Norfolk Island', 'NF');
        INSERT INTO public.country ("name", "iso") VALUES ('Northern Mariana Islands', 'MP');
        INSERT INTO public.country ("name", "iso") VALUES ('Norway', 'NO');
        INSERT INTO public.country ("name", "iso") VALUES ('Oman', 'OM');
        INSERT INTO public.country ("name", "iso") VALUES ('Pakistan', 'PK');
        INSERT INTO public.country ("name", "iso") VALUES ('Palau', 'PW');
        INSERT INTO public.country ("name", "iso") VALUES ('Panama', 'PA');
        INSERT INTO public.country ("name", "iso") VALUES ('Papua New Guinea', 'PG');
        INSERT INTO public.country ("name", "iso") VALUES ('Paraguay', 'PY');
        INSERT INTO public.country ("name", "iso") VALUES ('Peru', 'PE');
        INSERT INTO public.country ("name", "iso") VALUES ('Philippines', 'PH');
        INSERT INTO public.country ("name", "iso") VALUES ('Pitcairn', 'PN');
        INSERT INTO public.country ("name", "iso") VALUES ('Poland', 'PL');
        INSERT INTO public.country ("name", "iso") VALUES ('Portugal', 'PT');
        INSERT INTO public.country ("name", "iso") VALUES ('Puerto Rico', 'PR');
        INSERT INTO public.country ("name", "iso") VALUES ('Qatar', 'QA');
        INSERT INTO public.country ("name", "iso") VALUES ('Romania', 'RO');
        INSERT INTO public.country ("name", "iso") VALUES ('Russian Federation', 'RU');
        INSERT INTO public.country ("name", "iso") VALUES ('Rwanda', 'RW');
        INSERT INTO public.country ("name", "iso") VALUES ('Saint Kitts and Nevis', 'KN');
        INSERT INTO public.country ("name", "iso") VALUES ('Saint Lucia', 'LC');
        INSERT INTO public.country ("name", "iso") VALUES ('Saint Martin (French part)' ,'MF');
        INSERT INTO public.country ("name", "iso") VALUES ('Saint Pierre and Miquelon', 'PM');
        INSERT INTO public.country ("name", "iso") VALUES ('Saint Vincent and the Grenadines', 'VC');
        INSERT INTO public.country ("name", "iso") VALUES ('Samoa', 'WS');
        INSERT INTO public.country ("name", "iso") VALUES ('San Marino', 'SM');
        INSERT INTO public.country ("name", "iso") VALUES ('Sao Tome and Principe', 'ST');
        INSERT INTO public.country ("name", "iso") VALUES ('Saudi Arabia', 'SA');
        INSERT INTO public.country ("name", "iso") VALUES ('Senegal', 'SN');
        INSERT INTO public.country ("name", "iso") VALUES ('Serbia', 'RS');
        INSERT INTO public.country ("name", "iso") VALUES ('Seychelles', 'SC');
        INSERT INTO public.country ("name", "iso") VALUES ('Sierra Leone', 'SL');
        INSERT INTO public.country ("name", "iso") VALUES ('Singapore', 'SG');
        INSERT INTO public.country ("name", "iso") VALUES ('Sint Maarten (Dutch part)' ,'SX');
        INSERT INTO public.country ("name", "iso") VALUES ('Slovakia', 'SK');
        INSERT INTO public.country ("name", "iso") VALUES ('Slovenia', 'SI');
        INSERT INTO public.country ("name", "iso") VALUES ('Solomon Islands', 'SB');
        INSERT INTO public.country ("name", "iso") VALUES ('Somalia', 'SO');
        INSERT INTO public.country ("name", "iso") VALUES ('South Africa', 'ZA');
        INSERT INTO public.country ("name", "iso") VALUES ('South Georgia and the South Sandwich Islands', 'GS');
        INSERT INTO public.country ("name", "iso") VALUES ('South Sudan', 'SS');
        INSERT INTO public.country ("name", "iso") VALUES ('Spain', 'ES');
        INSERT INTO public.country ("name", "iso") VALUES ('Sri Lanka', 'LK');
        INSERT INTO public.country ("name", "iso") VALUES ('Sudan', 'SD');
        INSERT INTO public.country ("name", "iso") VALUES ('Suri"name"', 'SR');
        INSERT INTO public.country ("name", "iso") VALUES ('Svalbard and Jan Mayen', 'SJ');
        INSERT INTO public.country ("name", "iso") VALUES ('Swaziland', 'SZ');
        INSERT INTO public.country ("name", "iso") VALUES ('Sweden', 'SE');
        INSERT INTO public.country ("name", "iso") VALUES ('Switzerland', 'CH');
        INSERT INTO public.country ("name", "iso") VALUES ('Syrian Arab Republic', 'SY');
        INSERT INTO public.country ("name", "iso") VALUES ('Tajikistan', 'TJ');
        INSERT INTO public.country ("name", "iso") VALUES ('Thailand', 'TH');
        INSERT INTO public.country ("name", "iso") VALUES ('Timor-Leste', 'TL');
        INSERT INTO public.country ("name", "iso") VALUES ('Togo', 'TG');
        INSERT INTO public.country ("name", "iso") VALUES ('Tokelau', 'TK');
        INSERT INTO public.country ("name", "iso") VALUES ('Tonga', 'TO');
        INSERT INTO public.country ("name", "iso") VALUES ('Trinidad and Tobago', 'TT');
        INSERT INTO public.country ("name", "iso") VALUES ('Tunisia', 'TN');
        INSERT INTO public.country ("name", "iso") VALUES ('Turkey', 'TR');
        INSERT INTO public.country ("name", "iso") VALUES ('Turkmenistan', 'TM');
        INSERT INTO public.country ("name", "iso") VALUES ('Turks and Caicos Islands', 'TC');
        INSERT INTO public.country ("name", "iso") VALUES ('Tuvalu', 'TV');
        INSERT INTO public.country ("name", "iso") VALUES ('Uganda', 'UG');
        INSERT INTO public.country ("name", "iso") VALUES ('Ukraine', 'UA');
        INSERT INTO public.country ("name", "iso") VALUES ('United Arab Emirates', 'AE');
        INSERT INTO public.country ("name", "iso") VALUES ('United Kingdom', 'GB');
        INSERT INTO public.country ("name", "iso") VALUES ('United States', 'US');
        INSERT INTO public.country ("name", "iso") VALUES ('United States Minor Outlying Islands', 'UM');
        INSERT INTO public.country ("name", "iso") VALUES ('Uruguay', 'UY');
        INSERT INTO public.country ("name", "iso") VALUES ('Uzbekistan', 'UZ');
        INSERT INTO public.country ("name", "iso") VALUES ('Vanuatu', 'VU');
        INSERT INTO public.country ("name", "iso") VALUES ('Viet Nam', 'VN');
        INSERT INTO public.country ("name", "iso") VALUES ('Wallis and Futuna', 'WF');
        INSERT INTO public.country ("name", "iso") VALUES ('Western Sahara', 'EH');
        INSERT INTO public.country ("name", "iso") VALUES ('Yemen', 'YE');
        INSERT INTO public.country ("name", "iso") VALUES ('Zambia', 'ZM');
        INSERT INTO public.country ("name", "iso") VALUES ('Zimbabwe', 'ZW');`);
  }

  public async down(_: QueryRunner): Promise<void> {}
}
