import { MigrationInterface, QueryRunner } from 'typeorm';

export class LanguagesMigration1627223004686 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    queryRunner.query(`insert into public.language ("name") values ('Afrikaans');
        insert into public.language ("name") values ('Albanian');
        insert into public.language ("name") values ('Amharic');
        insert into public.language ("name") values ('Arabic');
        insert into public.language ("name") values ('Armenian');
        insert into public.language ("name") values ('Assamese');
        insert into public.language ("name") values ('Aymara');
        insert into public.language ("name") values ('Azeri');
        insert into public.language ("name") values ('Belarusian');
        insert into public.language ("name") values ('Bengali');
        insert into public.language ("name") values ('Bislama');
        insert into public.language ("name") values ('Bosnian');
        insert into public.language ("name") values ('Bulgarian');
        insert into public.language ("name") values ('Burmese');
        insert into public.language ("name") values ('Catalan');
        insert into public.language ("name") values ('Chinese');
        insert into public.language ("name") values ('Croatian');
        insert into public.language ("name") values ('Czech');
        insert into public.language ("name") values ('Danish');
        insert into public.language ("name") values ('Dari');
        insert into public.language ("name") values ('Dhivehi');
        insert into public.language ("name") values ('Dutch');
        insert into public.language ("name") values ('Dzongkha');
        insert into public.language ("name") values ('English');
        insert into public.language ("name") values ('Estonian');
        insert into public.language ("name") values ('Fijian');
        insert into public.language ("name") values ('Filipino');
        insert into public.language ("name") values ('Finnish');
        insert into public.language ("name") values ('French');
        insert into public.language ("name") values ('Gagauz');
        insert into public.language ("name") values ('Georgian');
        insert into public.language ("name") values ('German');
        insert into public.language ("name") values ('Greek');
        insert into public.language ("name") values ('Guaraní');
        insert into public.language ("name") values ('Gujarati');
        insert into public.language ("name") values ('Haitian Creole');
        insert into public.language ("name") values ('Hebrew');
        insert into public.language ("name") values ('Hindi');
        insert into public.language ("name") values ('Hiri Motu');
        insert into public.language ("name") values ('Hungarian');
        insert into public.language ("name") values ('Icelandic');
        insert into public.language ("name") values ('Indonesian');
        insert into public.language ("name") values ('Irish Gaelic');
        insert into public.language ("name") values ('Italian');
        insert into public.language ("name") values ('Japanese');
        insert into public.language ("name") values ('Kannada');
        insert into public.language ("name") values ('Kashmiri');
        insert into public.language ("name") values ('Kazakh');
        insert into public.language ("name") values ('Khmer');
        insert into public.language ("name") values ('Korean');
        insert into public.language ("name") values ('Kurdish');
        insert into public.language ("name") values ('Kyrgyz');
        insert into public.language ("name") values ('Lao');
        insert into public.language ("name") values ('Latvian');
        insert into public.language ("name") values ('Lithuanian');
        insert into public.language ("name") values ('Luxembourgish');
        insert into public.language ("name") values ('Macedonian');
        insert into public.language ("name") values ('Malagasy');
        insert into public.language ("name") values ('Malay');
        insert into public.language ("name") values ('Malayalam');
        insert into public.language ("name") values ('Maltese');
        insert into public.language ("name") values ('Marathi');
        insert into public.language ("name") values ('Moldovan');
        insert into public.language ("name") values ('Mongolian');
        insert into public.language ("name") values ('Montenegrin');
        insert into public.language ("name") values ('Māori');
        insert into public.language ("name") values ('Ndebele');
        insert into public.language ("name") values ('Nepali');
        insert into public.language ("name") values ('New Zealand Sign Language');
        insert into public.language ("name") values ('Northern Sotho');
        insert into public.language ("name") values ('Norwegian');
        insert into public.language ("name") values ('Oriya');
        insert into public.language ("name") values ('Papiamento');
        insert into public.language ("name") values ('Pashto');
        insert into public.language ("name") values ('Persian');
        insert into public.language ("name") values ('Polish');
        insert into public.language ("name") values ('Portuguese');
        insert into public.language ("name") values ('Punjabi');
        insert into public.language ("name") values ('Quechua');
        insert into public.language ("name") values ('Romanian');
        insert into public.language ("name") values ('Somali');
        insert into public.language ("name") values ('Sotho');
        insert into public.language ("name") values ('Spanish');
        insert into public.language ("name") values ('Swahili');
        insert into public.language ("name") values ('Swati');
        insert into public.language ("name") values ('Swedish');
        insert into public.language ("name") values ('Tajik');
        insert into public.language ("name") values ('Tamil');
        insert into public.language ("name") values ('Telugu');
        insert into public.language ("name") values ('Tetum');
        insert into public.language ("name") values ('Thai');
        insert into public.language ("name") values ('Tok Pisin');
        insert into public.language ("name") values ('Tsonga');
        insert into public.language ("name") values ('Tswana');
        insert into public.language ("name") values ('West Frisian');
        insert into public.language ("name") values ('Y"name"dish');
        insert into public.language ("name") values ('Zulu');`);
  }

  public async down(_: QueryRunner): Promise<void> {}
}
