version: "3.4"

services:
  echat-web:
    ports:
      - 3000:3000
    build:
      context: web/
      dockerfile: Dockerfile
      target: prod
    restart: always
    networks:
      - nginx-pm_default
  echat-server:
    # ports:
    #   - 4001:4001
    build:
      context: server/
      dockerfile: Dockerfile
      target: prod
    restart: always
    depends_on:
      - echat-db
    environment:
      - DATABASE_URL=postgres://postgres:9oQX2RUHuHzwjy@echat-db:5432/echat
    networks:
      - nginx-pm_default
  echat-db:
    image: postgres:14.1-alpine
    restart: always
    # ports:
      # - 5432:5432
    environment:
      - POSTGRES_PASSWORD=9oQX2RUHuHzwjy
      - POSTGRES_USER=postgres
      - POSTGRES_DB=echat
    volumes:
      - ~/pgdata:/var/lib/postgresql/data
    networks:
      - nginx-pm_default
  # echat-nginx:
  #   image: jonasal/nginx-certbot:latest
  #   restart: always
  #   ports: 
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./user_conf.d:/etc/nginx/user_conf.d
  #     - nginx_secrets:/etc/letsencrypt
  #   environment:
  #     CERTBOT_EMAIL: don.cryptus@gmail.com

networks:
  nginx-pm_default:
    external: false
    name: nginx-pm_default

# volumes:
#   nginx_secrets:
