version: "3.8"

services:
  echat-web:
    ports:
      - 3000
    build:
      context: web/
      dockerfile: Dockerfile
      target: prod
    restart: always
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.echat-web.rule=Host(`echat.myngz.com`)'
      - 'traefik.http.routers.echat-web.entrypoints=websecure'
      - 'traefik.http.routers.echat-web.tls.certresolver=letsencrypt'
  echat-server:
    ports:
      - 4001
    build:
      context: server/
      dockerfile: Dockerfile
      target: prod
    restart: always
    depends_on:
      - echat-db
    environment:
      - DATABASE_URL=postgres://postgres:9oQX2RUHuHzwjy@echat-db:5432/echat
    networks:
      - proxy
  echat-db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=9oQX2RUHuHzwjy
      - POSTGRES_USER=postgres
      - POSTGRES_DB=echat
    volumes:
      - ~/pgdata:/var/lib/postgresql/data
    networks:
      - proxy

networks:
  proxy:
    external: false
    name: proxy
