version: "3.3"


#### Docker delete All + Cache #####
# docker system prune -a

### Build DockerFile ###
# docker build -t nextjs .

### Docker run Container ###
# docker run -p 3000:3000 nextjs

### SSH in to Image ###
# docker run -it server sh

services:
  web:
    ports:
      - 3000:3000
    build:
      context: web/
      dockerfile: Dockerfile
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - web/.env.local
  server:
    ports:
      - 4001:4001
    build:
      context: server/
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - server/.env