version: "3.3"

services:
  web:
    ports:
      - 3000:3000
    build:
      context: web/
      dockerfile: Dockerfile
    volumes:
      - ./web:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - web/.env.local