version: "3.8"

services:
  echat-web:
    container_name: echat-web
    build:
      context: web/
      dockerfile: Dockerfile
      target: prod
    restart: always
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.echat-web.rule=Host(`echat.coding.global`)'
      - 'traefik.http.routers.echat-web.entrypoints=websecure'
      - 'traefik.http.routers.echat-web.tls.certresolver=letsencrypt'
      - 'traefik.http.services.echat-web.loadbalancer.server.port=3000'
  echat-server:
    container_name: echat-server
    build:
      context: server/
      dockerfile: Dockerfile
      target: prod
    restart: always
    depends_on:
      - echat-db
    environment:
      - DATABASE_URL=postgres://postgres:9oQX2RUHuHzwjy@echat-db:5432/echat
    networks:
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.echat-server.rule=Host(`echat.coding.global`) && PathPrefix(`/graphql`)'
      - 'traefik.http.routers.echat-server.entrypoints=websecure'
      - 'traefik.http.routers.echat-server.tls.certresolver=letsencrypt'
      - 'traefik.http.services.echat-server.loadbalancer.server.port=4001'
  echat-db:
    container_name: echat-db
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_PASSWORD=9oQX2RUHuHzwjy
      - POSTGRES_USER=postgres
      - POSTGRES_DB=echat
    networks:
      - proxy

networks:
  proxy:
    external: false
    name: proxy
