import "@fortawesome/fontawesome-svg-core/styles.css";
import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faDiscord,
  faTwitter,
  faFacebook,
  faSnapchat,
  faInstagram,
  faTwitch,
  faSteam,
  faTiktok,
} from "@fortawesome/free-brands-svg-icons";
import {
  faDollarSign,
  faTrash,
  faTrashAlt,
  faPenAlt,
  faCheck,
  faGamepad,
  faCaretRight,
  faMoon,
  faToolbox,
  faDoorOpen,
  faRunning,
  faTrophy,
  faCouch,
  faStar,
  faCoins,
  faBars,
  faSearch,
  faMars,
  faVenus,
  faTransgender,
  faImages,
  faStarHalf,
  faStarHalfAlt,
  faAngleDoubleRight,
  faAngleDoubleLeft,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faStarHalfAlt,
  faStarHalf,
  faImages,
  faMars,
  faVenus,
  faTransgender,
  faSearch,
  faBars,
  faCoins,
  faStar,
  faCouch,
  faTrophy,
  faRunning,
  faDoorOpen,
  faToolbox,
  faMoon,
  faCaretRight,
  faGamepad,
  faCheck,
  faPenAlt,
  faTrashAlt,
  faTrash,
  faDiscord,
  faTwitter,
  faFacebook,
  faSnapchat,
  faInstagram,
  faTwitch,
  faSteam,
  faTiktok,
  faDollarSign,
  faAngleDoubleRight,
  faAngleDoubleLeft
);
