export const __prod__ = 'production' === process.env.NODE_ENV;
export const GRAPHQL_SERVER_URL = __prod__
  ? '/graphql'
  : 'http://localhost:4001/graphql';

export const PERS = [
  { id: 1, name: 'Game' },
  { id: 2, name: '15 Min' },
  { id: 3, name: '30 Min' },
  { id: 4, name: '45 Min' },
  { id: 5, name: '60 Min' },
];

export const LEVELS = [
  { id: 1, name: 'Newbie' },
  { id: 2, name: 'Moderate' },
  { id: 3, name: 'Average' },
  { id: 4, name: 'Above Average' },
  { id: 5, name: 'Professional' },
  { id: 6, name: 'Master' },
  { id: 7, name: 'Legend' },
];

export const SCHEDULES = [
  {
    id: 1,
    name: 'Monday',
    from: new Date(0, 0, 0, 9, 30),
    to: new Date(0, 0, 0, 18, 30),
    available: true,
  },
  {
    id: 2,
    name: 'Tuesday',
    from: new Date(0, 0, 0, 9, 30),
    to: new Date(0, 0, 0, 18, 30),
    available: true,
  },
  {
    id: 3,
    name: 'Wednesday',
    from: new Date(0, 0, 0, 9, 30),
    to: new Date(0, 0, 0, 18, 30),
    available: true,
  },
  {
    id: 4,
    name: 'Thursday',
    from: new Date(0, 0, 0, 9, 30),
    to: new Date(0, 0, 0, 18, 30),
    available: true,
  },
  {
    id: 5,
    name: 'Friday',
    from: new Date(0, 0, 0, 9, 30),
    to: new Date(0, 0, 0, 18, 30),
    available: true,
  },
  {
    id: 6,
    name: 'Saturday',
    from: new Date(0, 0, 0, 9, 30),
    to: new Date(0, 0, 0, 18, 30),
    available: true,
  },
  {
    id: 7,
    name: 'Sunday',
    from: new Date(0, 0, 0, 9, 30),
    to: new Date(0, 0, 0, 18, 30),
    available: true,
  },
];

export const GENDERS = [
  { id: 1, name: 'Female' },
  { id: 2, name: 'Male' },
  { id: 3, name: 'Other' },
];
export const COUNTRIES = [
  { id: 1, name: 'Afghanistan' },
  { id: 2, name: 'Albania' },
  { id: 3, name: 'Algeria' },
  { id: 4, name: 'American Samoa' },
  { id: 5, name: 'Andorra' },
  { id: 6, name: 'Angola' },
  { id: 7, name: 'Anguilla' },
  { id: 8, name: 'Antarctica' },
  { id: 9, name: 'Antigua and Barbuda' },
  { id: 10, name: 'Argentina' },
  { id: 11, name: 'Armenia' },
  { id: 12, name: 'Aruba' },
  { id: 13, name: 'Australia' },
  { id: 14, name: 'Austria' },
  { id: 15, name: 'Azerbaijan' },
  { id: 16, name: 'Bahamas' },
  { id: 17, name: 'Bahrain' },
  { id: 18, name: 'Bangladesh' },
  { id: 19, name: 'Barbados' },
  { id: 20, name: 'Belarus' },
  { id: 21, name: 'Belgium' },
  { id: 22, name: 'Belize' },
  { id: 23, name: 'Benin' },
  { id: 24, name: 'Bermuda' },
  { id: 25, name: 'Bhutan' },
  { id: 26, name: 'Bosnia and Herzegovina' },
  { id: 27, name: 'Botswana' },
  { id: 28, name: 'Bouvet Island' },
  { id: 29, name: 'Brazil' },
  { id: 30, name: 'British Indian Ocean Territory' },
  { id: 31, name: 'Brunei Darussalam' },
  { id: 32, name: 'Bulgaria' },
  { id: 33, name: 'Burkina Faso' },
  { id: 34, name: 'Burundi' },
  { id: 35, name: 'Cambodia' },
  { id: 36, name: 'Cameroon' },
  { id: 37, name: 'Canada' },
  { id: 38, name: 'Cape Verde' },
  { id: 39, name: 'Cayman Islands' },
  { id: 40, name: 'Central African Republic' },
  { id: 41, name: 'Chad' },
  { id: 42, name: 'Chile' },
  { id: 43, name: 'China' },
  { id: 44, name: 'Christmas Island' },
  { id: 45, name: 'Cocos (Keeling) Islands' },
  { id: 46, name: 'Colombia' },
  { id: 47, name: 'Comoros' },
  { id: 48, name: 'Congo' },
  { id: 49, name: 'Cook Islands' },
  { id: 50, name: 'Costa Rica' },
  { id: 51, name: 'Croatia' },
  { id: 52, name: 'Cuba' },
  { id: 53, name: 'Cyprus' },
  { id: 54, name: 'Czech Republic' },
  { id: 55, name: 'Denmark' },
  { id: 56, name: 'Djibouti' },
  { id: 57, name: 'Dominica' },
  { id: 58, name: 'Dominican Republic' },
  { id: 59, name: 'Ecuador' },
  { id: 60, name: 'Egypt' },
  { id: 61, name: 'El Salvador' },
  { id: 62, name: 'Equatorial Guinea' },
  { id: 63, name: 'Eritrea' },
  { id: 64, name: 'Estonia' },
  { id: 65, name: 'Ethiopia' },
  { id: 66, name: 'Falkland Islands (Malvinas)' },
  { id: 67, name: 'Faroe Islands' },
  { id: 68, name: 'Fiji' },
  { id: 69, name: 'Finland' },
  { id: 70, name: 'France' },
  { id: 71, name: 'French Guiana' },
  { id: 72, name: 'French Polynesia' },
  { id: 73, name: 'French Southern Territories' },
  { id: 74, name: 'Gabon' },
  { id: 75, name: 'Gambia' },
  { id: 76, name: 'Georgia' },
  { id: 77, name: 'Germany' },
  { id: 78, name: 'Ghana' },
  { id: 79, name: 'Gibraltar' },
  { id: 80, name: 'Greece' },
  { id: 81, name: 'Greenland' },
  { id: 82, name: 'Grenada' },
  { id: 83, name: 'Guadeloupe' },
  { id: 84, name: 'Guam' },
  { id: 85, name: 'Guatemala' },
  { id: 86, name: 'Guernsey' },
  { id: 87, name: 'Guinea' },
  { id: 88, name: 'Guinea-Bissau' },
  { id: 89, name: 'Guyana' },
  { id: 90, name: 'Haiti' },
  { id: 91, name: 'Heard Island and McDonald Islands' },
  { id: 92, name: 'Holy See (Vatican City State)' },
  { id: 93, name: 'Honduras' },
  { id: 94, name: 'Hong Kong' },
  { id: 95, name: 'Hungary' },
  { id: 96, name: 'Iceland' },
  { id: 97, name: 'India' },
  { id: 98, name: 'Indonesia' },
  { id: 99, name: 'Iraq' },
  { id: 100, name: 'Ireland' },
  { id: 101, name: 'Isle of Man' },
  { id: 102, name: 'Israel' },
  { id: 103, name: 'Italy' },
  { id: 104, name: 'Jamaica' },
  { id: 105, name: 'Japan' },
  { id: 106, name: 'Jersey' },
  { id: 107, name: 'Jordan' },
  { id: 108, name: 'Kazakhstan' },
  { id: 109, name: 'Kenya' },
  { id: 110, name: 'Kiribati' },
  { id: 111, name: 'Kuwait' },
  { id: 112, name: 'Kyrgyzstan' },
  { id: 113, name: 'Lao Peoples Democratic Republic' },
  { id: 114, name: 'Latvia' },
  { id: 115, name: 'Lebanon' },
  { id: 116, name: 'Lesotho' },
  { id: 117, name: 'Liberia' },
  { id: 118, name: 'Libya' },
  { id: 119, name: 'Liechtenstein' },
  { id: 120, name: 'Lithuania' },
  { id: 121, name: 'Luxembourg' },
  { id: 122, name: 'Macao' },
  { id: 123, name: 'Madagascar' },
  { id: 124, name: 'Malawi' },
  { id: 125, name: 'Malaysia' },
  { id: 126, name: 'Maldives' },
  { id: 127, name: 'Mali' },
  { id: 128, name: 'Malta' },
  { id: 129, name: 'Marshall Islands' },
  { id: 130, name: 'Martinique' },
  { id: 131, name: 'Mauritania' },
  { id: 132, name: 'Mauritius' },
  { id: 133, name: 'Mayotte' },
  { id: 134, name: 'Mexico' },
  { id: 135, name: 'Monaco' },
  { id: 136, name: 'Mongolia' },
  { id: 137, name: 'Montenegro' },
  { id: 138, name: 'Montserrat' },
  { id: 139, name: 'Morocco' },
  { id: 140, name: 'Mozambique' },
  { id: 141, name: 'Myanmar' },
  { id: 142, name: 'Namibia' },
  { id: 143, name: 'Nauru' },
  { id: 144, name: 'Nepal' },
  { id: 145, name: 'Netherlands' },
  { id: 146, name: 'New Caledonia' },
  { id: 147, name: 'New Zealand' },
  { id: 148, name: 'Nicaragua' },
  { id: 149, name: 'Niger' },
  { id: 150, name: 'Nigeria' },
  { id: 151, name: 'Niue' },
  { id: 152, name: 'Norfolk Island' },
  { id: 153, name: 'Northern Mariana Islands' },
  { id: 154, name: 'Norway' },
  { id: 155, name: 'Oman' },
  { id: 156, name: 'Pakistan' },
  { id: 157, name: 'Palau' },
  { id: 158, name: 'Panama' },
  { id: 159, name: 'Papua New Guinea' },
  { id: 160, name: 'Paraguay' },
  { id: 161, name: 'Peru' },
  { id: 162, name: 'Philippines' },
  { id: 163, name: 'Pitcairn' },
  { id: 164, name: 'Poland' },
  { id: 165, name: 'Portugal' },
  { id: 166, name: 'Puerto Rico' },
  { id: 167, name: 'Qatar' },
  { id: 168, name: 'Romania' },
  { id: 169, name: 'Russian Federation' },
  { id: 170, name: 'Rwanda' },
  { id: 171, name: 'Saint Kitts and Nevis' },
  { id: 172, name: 'Saint Lucia' },
  { id: 173, name: 'Saint Martin (French part)' },
  { id: 174, name: 'Saint Pierre and Miquelon' },
  { id: 175, name: 'Saint Vincent and the Grenadines' },
  { id: 176, name: 'Samoa' },
  { id: 177, name: 'San Marino' },
  { id: 178, name: 'Sao Tome and Principe' },
  { id: 179, name: 'Saudi Arabia' },
  { id: 180, name: 'Senegal' },
  { id: 181, name: 'Serbia' },
  { id: 182, name: 'Seychelles' },
  { id: 183, name: 'Sierra Leone' },
  { id: 184, name: 'Singapore' },
  { id: 185, name: 'Sint Maarten (Dutch part)' },
  { id: 186, name: 'Slovakia' },
  { id: 187, name: 'Slovenia' },
  { id: 188, name: 'Solomon Islands' },
  { id: 189, name: 'Somalia' },
  { id: 190, name: 'South Africa' },
  { id: 191, name: 'South Georgia and the South Sandwich Islands' },
  { id: 192, name: 'South Sudan' },
  { id: 193, name: 'Spain' },
  { id: 194, name: 'Sri Lanka' },
  { id: 195, name: 'Sudan' },
  { id: 196, name: 'Suri"name"' },
  { id: 197, name: 'Svalbard and Jan Mayen' },
  { id: 198, name: 'Swaziland' },
  { id: 199, name: 'Sweden' },
  { id: 200, name: 'Switzerland' },
  { id: 201, name: 'Syrian Arab Republic' },
  { id: 202, name: 'Tajikistan' },
  { id: 203, name: 'Thailand' },
  { id: 204, name: 'Timor-Leste' },
  { id: 205, name: 'Togo' },
  { id: 206, name: 'Tokelau' },
  { id: 207, name: 'Tonga' },
  { id: 208, name: 'Trinidad and Tobago' },
  { id: 209, name: 'Tunisia' },
  { id: 210, name: 'Turkey' },
  { id: 211, name: 'Turkmenistan' },
  { id: 212, name: 'Turks and Caicos Islands' },
  { id: 213, name: 'Tuvalu' },
  { id: 214, name: 'Uganda' },
  { id: 215, name: 'Ukraine' },
  { id: 216, name: 'United Arab Emirates' },
  { id: 217, name: 'United Kingdom' },
  { id: 218, name: 'United States' },
  { id: 219, name: 'United States Minor Outlying Islands' },
  { id: 220, name: 'Uruguay' },
  { id: 221, name: 'Uzbekistan' },
  { id: 222, name: 'Vanuatu' },
  { id: 223, name: 'Viet Nam' },
  { id: 224, name: 'Wallis and Futuna' },
  { id: 225, name: 'Western Sahara' },
  { id: 226, name: 'Yemen' },
  { id: 227, name: 'Zambia' },
  { id: 228, name: 'Zimbabwe' },
];
export const LANGUAGES = [
  { id: 1, name: 'Afrikaans' },
  { id: 2, name: 'Albanian' },
  { id: 3, name: 'Amharic' },
  { id: 4, name: 'Arabic' },
  { id: 5, name: 'Armenian' },
  { id: 6, name: 'Assamese' },
  { id: 7, name: 'Aymara' },
  { id: 8, name: 'Azeri' },
  { id: 9, name: 'Belarusian' },
  { id: 10, name: 'Bengali' },
  { id: 11, name: 'Bislama' },
  { id: 12, name: 'Bosnian' },
  { id: 13, name: 'Bulgarian' },
  { id: 14, name: 'Burmese' },
  { id: 15, name: 'Catalan' },
  { id: 16, name: 'Chinese' },
  { id: 17, name: 'Croatian' },
  { id: 18, name: 'Czech' },
  { id: 19, name: 'Danish' },
  { id: 20, name: 'Dari' },
  { id: 21, name: 'Dhivehi' },
  { id: 22, name: 'Dutch' },
  { id: 23, name: 'Dzongkha' },
  { id: 24, name: 'English' },
  { id: 25, name: 'Estonian' },
  { id: 26, name: 'Fijian' },
  { id: 27, name: 'Filipino' },
  { id: 28, name: 'Finnish' },
  { id: 29, name: 'French' },
  { id: 30, name: 'Gagauz' },
  { id: 31, name: 'Georgian' },
  { id: 32, name: 'German' },
  { id: 33, name: 'Greek' },
  { id: 34, name: 'Guaraní' },
  { id: 35, name: 'Gujarati' },
  { id: 36, name: 'Haitian Creole' },
  { id: 37, name: 'Hebrew' },
  { id: 38, name: 'Hindi' },
  { id: 39, name: 'Hiri Motu' },
  { id: 40, name: 'Hungarian' },
  { id: 41, name: 'Icelandic' },
  { id: 42, name: 'Indonesian' },
  { id: 43, name: 'Irish Gaelic' },
  { id: 44, name: 'Italian' },
  { id: 45, name: 'Japanese' },
  { id: 46, name: 'Kannada' },
  { id: 47, name: 'Kashmiri' },
  { id: 48, name: 'Kazakh' },
  { id: 49, name: 'Khmer' },
  { id: 50, name: 'Korean' },
  { id: 51, name: 'Kurdish' },
  { id: 52, name: 'Kyrgyz' },
  { id: 53, name: 'Lao' },
  { id: 54, name: 'Latvian' },
  { id: 55, name: 'Lithuanian' },
  { id: 56, name: 'Luxembourgish' },
  { id: 57, name: 'Macedonian' },
  { id: 58, name: 'Malagasy' },
  { id: 59, name: 'Malay' },
  { id: 60, name: 'Malayalam' },
  { id: 61, name: 'Maltese' },
  { id: 62, name: 'Marathi' },
  { id: 63, name: 'Moldovan' },
  { id: 64, name: 'Mongolian' },
  { id: 65, name: 'Montenegrin' },
  { id: 66, name: 'Māori' },
  { id: 67, name: 'Ndebele' },
  { id: 68, name: 'Nepali' },
  { id: 69, name: 'New Zealand Sign Language' },
  { id: 70, name: 'Northern Sotho' },
  { id: 71, name: 'Norwegian' },
  { id: 72, name: 'Oriya' },
  { id: 73, name: 'Papiamento' },
  { id: 74, name: 'Pashto' },
  { id: 75, name: 'Persian' },
  { id: 76, name: 'Polish' },
  { id: 77, name: 'Portuguese' },
  { id: 78, name: 'Punjabi' },
  { id: 79, name: 'Quechua' },
  { id: 80, name: 'Romanian' },
  { id: 81, name: 'Somali' },
  { id: 82, name: 'Sotho' },
  { id: 83, name: 'Spanish' },
  { id: 84, name: 'Swahili' },
  { id: 85, name: 'Swati' },
  { id: 86, name: 'Swedish' },
  { id: 87, name: 'Tajik' },
  { id: 88, name: 'Tamil' },
  { id: 89, name: 'Telugu' },
  { id: 90, name: 'Tetum' },
  { id: 91, name: 'Thai' },
  { id: 92, name: 'Tok Pisin' },
  { id: 93, name: 'Tsonga' },
  { id: 94, name: 'Tswana' },
  { id: 95, name: 'West Frisian' },
  { id: 96, name: 'Y"name"dish' },
  { id: 97, name: 'Zulu' },
];
export const HOURS = [
  { id: 0, name: '0' },
  { id: 1, name: '1' },
  { id: 2, name: '2' },
  { id: 3, name: '3' },
  { id: 4, name: '4' },
  { id: 5, name: '5' },
  { id: 6, name: '6' },
  { id: 7, name: '7' },
  { id: 8, name: '8' },
  { id: 9, name: '9' },
  { id: 10, name: '10' },
  { id: 11, name: '11' },
  { id: 12, name: '12' },
  { id: 13, name: '13' },
  { id: 14, name: '14' },
  { id: 15, name: '15' },
  { id: 16, name: '16' },
  { id: 17, name: '17' },
  { id: 18, name: '18' },
  { id: 19, name: '19' },
  { id: 20, name: '20' },
  { id: 21, name: '21' },
  { id: 22, name: '22' },
  { id: 23, name: '23' },
];
export const AGES = [
  { id: 18, name: '18' },
  { id: 19, name: '19' },
  { id: 20, name: '20' },
  { id: 21, name: '21' },
  { id: 22, name: '22' },
  { id: 23, name: '23' },
  { id: 24, name: '24' },
  { id: 25, name: '25' },
  { id: 26, name: '26' },
  { id: 27, name: '27' },
  { id: 28, name: '28' },
  { id: 29, name: '29' },
  { id: 30, name: '30' },
  { id: 31, name: '31' },
  { id: 32, name: '32' },
  { id: 33, name: '33' },
  { id: 34, name: '34' },
  { id: 35, name: '35' },
  { id: 36, name: '36' },
  { id: 37, name: '37' },
  { id: 38, name: '38' },
  { id: 39, name: '39' },
  { id: 40, name: '40' },
  { id: 41, name: '41' },
  { id: 42, name: '42' },
  { id: 43, name: '43' },
  { id: 44, name: '44' },
  { id: 45, name: '45' },
  { id: 46, name: '46' },
  { id: 47, name: '47' },
  { id: 48, name: '48' },
  { id: 49, name: '49' },
  { id: 50, name: '50' },
  { id: 51, name: '51' },
  { id: 52, name: '52' },
  { id: 53, name: '53' },
  { id: 54, name: '54' },
  { id: 55, name: '55' },
  { id: 56, name: '56' },
  { id: 57, name: '57' },
  { id: 58, name: '58' },
  { id: 59, name: '59' },
  { id: 60, name: '60' },
  { id: 61, name: '61' },
  { id: 62, name: '62' },
  { id: 63, name: '63' },
  { id: 64, name: '64' },
  { id: 65, name: '65' },
  { id: 66, name: '66' },
  { id: 67, name: '67' },
  { id: 68, name: '68' },
  { id: 69, name: '69' },
  { id: 70, name: '70' },
  { id: 71, name: '71' },
  { id: 72, name: '72' },
  { id: 73, name: '73' },
  { id: 74, name: '74' },
  { id: 75, name: '75' },
  { id: 76, name: '76' },
  { id: 77, name: '77' },
  { id: 78, name: '78' },
  { id: 79, name: '79' },
  { id: 80, name: '80' },
  { id: 81, name: '81' },
  { id: 82, name: '82' },
  { id: 83, name: '83' },
  { id: 84, name: '84' },
  { id: 85, name: '85' },
  { id: 86, name: '86' },
  { id: 87, name: '87' },
  { id: 88, name: '88' },
  { id: 89, name: '89' },
  { id: 90, name: '90' },
  { id: 91, name: '91' },
  { id: 92, name: '92' },
  { id: 93, name: '93' },
  { id: 94, name: '94' },
  { id: 95, name: '95' },
  { id: 96, name: '96' },
  { id: 97, name: '97' },
  { id: 98, name: '98' },
  { id: 99, name: '99' },
];
