name: Docker Prod

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Create env file
        run: |
          touch .env
          echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
          echo SERVER_PORT=${{ secrets.SERVER_PORT }} >> .env
          echo SESSION_SECRET=${{ secrets.SESSION_SECRET }} >> .env
          echo CORS_ORIGIN=${{ secrets.CORS_ORIGIN }} >> .env
          echo SMPT_HOST=${{ secrets.SMPT_HOST }} >> .env
          echo SMTP_PORT=${{ secrets.SMTP_PORT }} >> .env
          echo SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }} >> .env
          echo CLOUDINARY_CLOUD_NAME=${{ secrets.CLOUDINARY_CLOUD_NAME }} >> .env
          echo CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }} >> .env
          echo CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }} >> .env
          echo CLOUDINARY_URL=${{ secrets.CLOUDINARY_URL }} >> .env
          echo TWITCH_CLIENT_ID=${{ secrets.TWITCH_CLIENT_ID }} >> .env
          echo TWITCH_CLIENT_SECRET=${{ secrets.TWITCH_CLIENT_SECRET }} >> .env
          cat .env

      - name: Copy env to Server
        run: mv .env ./server

      - name: Docker run
        run: docker compose -f docker-compose.prod.yml up -d --force-recreate --build
